import random

# List of fun facts
fun_facts = [
    "A group of flamingos is called a 'flamboyance.'",
    "There's enough DNA in the human body to stretch from the sun to Pluto and back—17 times.",
    "Sharks have been around longer than trees.",
    "Bananas are berries, but strawberries aren't.",
    "Honey never spoils—it’s been found in ancient Egyptian tombs and is still edible.",
    "Octopuses have three hearts.",
    "Wombat poop is cube-shaped.",
    "Some cats are allergic to humans.",
    "Sloths can take up to a month to digest food.",
    "A day on Venus is longer than a year on Venus.",
    "The Eiffel Tower can grow more than 6 inches during summer due to heat expansion.",
    "The unicorn is the national animal of Scotland.",
    "Dolphins have names for each other.",
    "There are more stars in the universe than grains of sand on Earth.",
    "The inventor of the frisbee was turned into a frisbee after he died.",
    "Butterflies taste with their feet.",
    "Cows have best friends and can get stressed when separated.",
    "A single strand of spider silk is five times stronger than steel of the same diameter.",
    "Humans share 60% of their DNA with bananas.",
    "Cleopatra lived closer in time to the invention of the iPhone than to the construction of the Great Pyramid.",
    "Jellyfish are considered biologically immortal—they don't age and can regenerate cells.",
    "A day on Mars is just over 24 hours long, making it the closest planet to Earth’s day length.",
    "Turtles can breathe through their butts.",
    "Tomatoes were once considered poisonous in Europe.",
    "Sea otters hold hands while sleeping to avoid drifting apart.",
    "A group of crows is called a 'murder.'",
    "Horses and cows can sleep standing up, but they can only dream lying down.",
    "There's a species of jellyfish that can age backward, potentially living forever.",
    "A human sneeze can travel at up to 100 miles per hour.",
    "Pineapples take about two years to grow.",
    "Earthworms have five hearts.",
    "Elephants are the only animals that can't jump.",
    "The shortest war in history lasted 38 to 45 minutes between Britain and Zanzibar in 1896.",
    "Sharks are the only fish that can blink with both eyes.",
    "A single cloud can weigh more than 1 million pounds.",
    "It would take 1,200,000 mosquitoes to fully drain a human of blood.",
    "Snails can sleep for up to three years.",
    "The largest living organism is a fungus in Oregon, covering over 2,385 acres.",
    "Humans are the only animals that blush.",
    "An ostrich's eye is bigger than its brain.",
    "A blue whale’s heart can weigh as much as a car.",
    "The first oranges weren’t orange—they were green.",
    "The electric eel can produce a shock of up to 600 volts.",
    "Koalas sleep up to 22 hours a day.",
    "Ants can carry up to 50 times their own body weight.",
    "The smell of freshly cut grass is actually a plant distress call.",
    "An octopus has nine brains—one central brain and one for each arm.",
    "The longest hiccuping spree lasted 68 years.",
    "A bolt of lightning contains enough energy to toast 100,000 slices of bread.",
    "There’s a species of frog that can freeze without dying.",
    "Humans share about 98.7% of their DNA with chimpanzees.",
    "Coca-Cola was originally green.",
    "The human nose can remember 50,000 different scents.",
    "Wolves can communicate through facial expressions.",
    "The fingerprints of a koala are almost indistinguishable from a human's.",
    "Male seahorses carry the babies instead of females.",
    "Squirrels plant thousands of new trees each year simply by forgetting where they buried their acorns.",
    "The word 'dreamt' is the only word in the English language that ends with 'mt.'",
    "A group of owls is called a 'parliament.'",
    "The wood frog can hold its pee for up to eight months.",
    "Starfish have no brains or blood.",
    "Polar bear fur is actually transparent, not white.",
    "Pigeons can recognize themselves in a mirror.",
    "Kangaroos can't walk backward.",
    "The Eiffel Tower was initially meant to be dismantled after 20 years.",
    "Dragonflies can fly up to 60 miles per hour.",
    "Slugs have four noses.",
    "A snail's mouth is no larger than the head of a pin, but it can contain over 25,000 teeth.",
    "A giraffe’s tongue is so long it can lick its own ears.",
    "The word 'typewriter' is the longest word you can type using only the top row of a keyboard.",
    "A rhinoceros's horn is made of hair.",
    "Hummingbirds are the only birds that can fly backward.",
    "The largest snowflake ever recorded was 15 inches wide.",
    "Penguins propose to their mates with a pebble.",
    "Goldfish can recognize their owners.",
    "A bolt of lightning is five times hotter than the surface of the sun.",
    "An ant can survive underwater for up to 24 hours.",
    "The tongue of a blue whale weighs as much as an elephant.",
    "A dragonfly has a 360-degree field of vision.",
    "There are more fake flamingos in the world than real ones.",
    "Tigers have striped skin, not just striped fur.",
    "A cockroach can live for a week without its head.",
    "Humans and giraffes have the same number of neck vertebrae—seven.",
    "A crocodile can't stick its tongue out.",
    "You can hear a blue whale's heartbeat from over 2 miles away.",
    "The heart of a shrimp is located in its head.",
    "Ketchup was once used as medicine.",
    "Spiders can regrow lost legs.",
    "Frogs absorb water through their skin, so they don’t need to drink.",
    "Butterflies can see ultraviolet light.",
    "Some turtles can breathe through their skin.",
    "The world's oldest toy is a stick.",
    "Rats laugh when tickled.",
    "Mosquitoes are attracted to people who have just eaten bananas.",
    "A group of porcupines is called a 'prickle.'",
    "A blue whale's tongue can weigh more than an elephant.",
    "The loudest sound produced by any animal is made by the sperm whale, reaching up to 230 decibels.",
    "A cheetah can accelerate from 0 to 60 miles per hour in just a few seconds.",
    "A goldfish can live up to 40 years.",
    "A group of pandas is called an 'embarrassment.'",
    "The average human body contains enough fat to make seven bars of soap.",
    "There are more lifeforms living on your skin than there are people on Earth.",
    "Some hummingbirds weigh less than a penny.",
    "The longest recorded flight of a chicken lasted 13 seconds.",
    "A newborn kangaroo is small enough to fit inside a teaspoon.",
    "Snakes can help predict earthquakes.",
    "A shrimp's heart is located in its head.",
    "The fingerprints of koalas are almost indistinguishable from humans'.",
    "Cows have four stomachs to help them digest their food.",
    "The male seahorse is the one that gives birth, not the female.",
    "A flea can jump 350 times its body length.",
    "Giraffes have no vocal cords.",
    "Polar bears are left-handed.",
    "The longest recorded flight of a chicken is 13 seconds.",
    "Butterflies can taste with their feet."
    "A jellyfish is 95% water.",
    "Bees communicate by dancing.",
    "The fingerprints of a koala are so similar to humans that they could taint crime scenes.",
    "Ants never sleep.",
    "The only mammals capable of flight are bats.",
    "A giraffe can clean its ears with its 21-inch tongue.",
    "The shortest commercial flight in the world is 57 seconds long.",
    "A group of ravens is called an 'unkindness.'",
    "Pigeons can learn to recognize all 26 letters of the English alphabet.",
    "Reindeer eyes turn blue in the winter to help them see at lower light levels.",
    "Elephants can 'hear' with their feet, detecting seismic vibrations.",
    "Humans shed about 600,000 particles of skin every hour.",
    "A sea cucumber can eject its internal organs as a defense mechanism.",
    "Penguins can drink seawater; they have a gland that filters out the salt.",
    "Some species of ant can create 'living bridges' by linking their bodies together.",
    "Seahorses mate for life, and the males carry the babies.",
    "A tarantula can survive for over two years without food.",
    "A dragonfly can live for up to a year, but it spends most of its life as a nymph underwater.",
    "Bamboo can grow up to 3 feet in a single day.",
    "Elephants can smell water from up to 12 miles away.",
    "The world's smallest fruit is the Wolffia globosa, or watermeal, which is the size of a grain of sand.",
    "The blue whale is the loudest animal on Earth.",
    "A group of ferrets is called a 'business.'",
    "A rhinoceros's horn is made entirely of keratin, the same substance as human hair and nails.",
    "The giant squid has the largest eyes in the animal kingdom, up to 10 inches in diameter.",
    "Rats and mice are ticklish and enjoy being tickled.",
    "The average person walks the equivalent of five times around the world in their lifetime.",
    "The mantis shrimp can punch with the force of a bullet.",
    "A newborn blue whale gains about 200 pounds per day.",
    "The flamingo's pink color comes from the food it eats—mostly shrimp and algae.",
    "Crocodiles can go for months without eating a meal.",
    "A group of giraffes is called a 'tower.'",
    "A bat can eat up to 1,000 mosquitoes in a single hour.",
    "The horned lizard can squirt blood from its eyes as a defense mechanism.",
    "The world's largest snowflake on record was 15 inches wide and 8 inches thick.",
    "Dolphins sleep with one eye open to stay alert for predators.",
    "Sea stars (starfish) have no brains and no blood.",
    "Humans can’t breathe and swallow at the same time.",
    "The planet Uranus was originally named 'George.'",
    "Male lions sleep up to 20 hours a day.",
    "Sharks are immune to all known diseases.",
    "A cat's purr has been shown to have healing properties.",
    "An octopus's blood is blue due to high copper levels.",
    "Penguins can leap up to 9 feet out of the water.",
    "A shrimp's heart is located in its head.",
    "The praying mantis is the only insect that can turn its head from side to side.",
    "Tigers' skin is striped, just like their fur.",
    "A blue whale's tongue weighs as much as an elephant.",
    "Some turtles can breathe through their butts.",
    "There are more bacteria in your mouth than there are people on Earth.",
    "The sloth's digestive process can take up to a month to complete.",
    "Flamingos bend their legs at the ankle, not the knee.",
    "The average adult human has about 100,000 miles of blood vessels in their body.",
    "Horses can sleep both standing up and lying down.",
    "Cats have over 100 vocal sounds, while dogs have only about 10.",
    "A jellyfish can evaporate in the sun because it is 95% water.",
    "The moon has moonquakes, just as Earth has earthquakes.",
    "A starfish can regenerate lost arms.",
    "Frogs can't vomit—if they need to, they eject their entire stomach.",
    "A group of frogs is called an 'army.'",
    "Cows can produce more milk when they listen to slow music.",
    "Hummingbirds flap their wings about 80 times per second.",
    "A chameleon's tongue is twice the length of its body.",
    "Some species of bats can live for more than 30 years.",
    "There are more stars in space than there are grains of sand on every beach on Earth.",
    "The shortest complete sentence in the English language is 'Go.'",
    "A crocodile's tongue is immobile, and it cannot stick its tongue out.",
    "Humans share 99.9% of their DNA with every other human.",
    "In a room of 23 people, there's a 50% chance two people share the same birthday.",
    "Tigers are excellent swimmers and can swim several kilometers at a time.",
    "The giant Pacific octopus has three hearts and blue blood.",
    "Humans share around 60% of their DNA with fruit flies.",
    "The only letter not appearing in the periodic table is the letter 'J.'",
    "A group of jellyfish is called a 'smack.'",
    "A housefly hums in the key of F.",
    "The world's oldest known living tree is over 5,000 years old.",
    "A kangaroo can't hop if its tail is lifted off the ground.",
    "The 'M’s in M&M’s stand for Mars and Murrie, the last names of the candy’s founders.",
    "Wombats have cube-shaped poop to mark their territory.",
    "Humans have jumped farther on the Moon than the highest jump on Earth.",
    "The Amazon rainforest produces 20% of the world’s oxygen supply.",
    "Sharks can detect a drop of blood in the ocean from up to a mile away.",
    "Bananas are naturally radioactive due to their potassium content.",
    "Pigeons were trained to deliver messages in wartime and could fly up to 600 miles to reach their destination.",
    "A single strand of human hair can support up to 100 grams in weight.",
    "An ostrich's eye is bigger than its brain.",
    "A flamingo can only eat when its head is upside down.",
    "The light from the sun takes about 8 minutes to reach Earth.",
    "A day on Venus is longer than its year.",
    "The fingerprints of a koala are almost indistinguishable from a human's.",
    "Octopuses have copper-based blood, which turns blue when exposed to oxygen.",
    "The pupil of a goat’s eye is rectangular, not round."
]



# Select a random fun fact
selected_fact = random.choice(fun_facts)

# Read the current README.md file
with open("README.md", "r") as file:
    readme_content = file.read()

# Define the section markers
start_marker = "<!-- FUN_FACT_SECTION -->"
end_marker = "<!-- END_FUN_FACT_SECTION -->"

# Ensure the markers exist
if start_marker in readme_content and end_marker in readme_content:
    # Replace the placeholder with the new fun fact, maintaining correct formatting
    new_readme_content = (
        readme_content.split(start_marker)[0]
        + start_marker
        + "\n"  # Maintain new line after the marker
        + selected_fact  # Add the fun fact directly
        + "\n"  # Maintain new line before the end marker
        + end_marker
        + readme_content.split(end_marker)[1]
    )

    # Write the updated content back to README.md
    with open("README.md", "w") as file:
        file.write(new_readme_content)

else:
    print(f"Markers not found in README.md! Ensure the markers {start_marker} and {end_marker} exist.")
